version: '3.7'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    # volumes:
    # - postgres-data:/var/lib/postgresql/data/
    networks:
      - api

  # keycloak:
  #   image: quay.io/keycloak/keycloak:15.0.1
  #   container_name: keycloak
  #   restart: unless-stopped
  #   environment:
  #     - KEYCLOAK_USER=admin
  #     - KEYCLOAK_PASSWORD=admin
  #   ports:
  #     - 8081:8080
  #   networks:
  #     - api

# volumes:
# postgres-data:

networks:
  api:
    driver: bridge
